# -*- coding: utf-8 -*-
"""Privacy_JSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EA9Iq5oWFKEU3inXzpKpR9N-8QIPn2uj
"""

!pip install spacy

!python -m spacy download en_core_web_lg

import json
import re
from collections import defaultdict

import spacy

nlp = spacy.load("en_core_web_lg")

import json
import re
from collections import defaultdict

import spacy

nlp = spacy.load("en_core_web_lg")

# --------------------------------------------------
# Counters and mappings
# --------------------------------------------------

entity_mapping = {}
reverse_mapping = {}

counters = defaultdict(int)

# --------------------------------------------------
# Regex patterns – only the ones you want to hide
# --------------------------------------------------

REGEX_PATTERNS = {
    # Finnish personal identity code (ID card number)
    "FINNISH_HETU": r"\b\d{6}[+-A]\d{3}[0-9A-Y]\b",
    # Passport number (1-2 letters + 6-9 digits)
    "PASSPORT": r"\b[A-Z]{1,2}[0-9]{6,9}\b",
    # Phone number
    "PHONE": r"(\+?\d[\d\s\-]{7,}\d)",
}

# --------------------------------------------------
# Helper
# --------------------------------------------------

def create_placeholder(prefix, original):
    if original in entity_mapping:
        return entity_mapping[original]

    counters[prefix] += 1
    placeholder = f"<{prefix}_{counters[prefix]}>"

    entity_mapping[original] = placeholder
    reverse_mapping[placeholder] = original

    return placeholder

# --------------------------------------------------
# Regex anonymization
# --------------------------------------------------

def anonymize_regex(text):
    for prefix, pattern in REGEX_PATTERNS.items():
        def repl(match):
            return create_placeholder(prefix, match.group())
        text = re.sub(pattern, repl, text)
    return text

# --------------------------------------------------
# Decide entity type – only PERSON is anonymised
# --------------------------------------------------

def get_entity_prefix(ent):
    if ent.label_ == "PERSON":
        return "PERSON"
    return None  # ignore all other entity types

# --------------------------------------------------
# NER anonymization (only names)
# --------------------------------------------------

def anonymize_entities(text):
    doc = nlp(text)
    entities = sorted(doc.ents, key=lambda x: len(x.text), reverse=True)

    for ent in entities:
        prefix = get_entity_prefix(ent)
        if prefix is None:
            continue
        placeholder = create_placeholder(prefix, ent.text)
        text = re.sub(
            r"\b{}\b".format(re.escape(ent.text)),
            placeholder,
            text,
        )
    return text

# --------------------------------------------------
# Address redaction – keep only city and country
# --------------------------------------------------

def redact_addresses(text):
    """
    Detect patterns like "number + street name, city, country"
    and replace the whole span with just the city and country.
    """
    doc = nlp(text)
    # find all GPE entities (city/country) that might be part of an address
    gpe_entities = [ent for ent in doc.ents if ent.label_ == "GPE"]

    # nothing to do
    if not gpe_entities:
        return text

    # build spans to replace, from end to start to avoid index shifts
    spans_to_replace = []
    for ent in gpe_entities:
        # Look backwards up to 6 tokens for a digit (house number)
        start_tok = ent.start
        found_digit = False
        for i in range(ent.start - 1, max(ent.start - 7, -1), -1):
            if doc[i].like_num and any(c.isdigit() for c in doc[i].text):
                # token contains a digit – treat as possible house number
                start_tok = i
                found_digit = True
                break
        if not found_digit:
            continue  # no number before this city/country, ignore

        # extend the span to include all consecutive GPEs that follow
        end_tok = ent.end
        for i in range(ent.end, len(doc)):
            if doc[i].ent_type_ == "GPE":
                end_tok = i + 1
            else:
                break

        # build the replacement: only the GPE texts, joined by a comma
        kept_parts = []
        for tok in doc[start_tok:end_tok]:
            if tok.ent_type_ == "GPE":
                kept_parts.append(tok.text)
        if not kept_parts:
            continue

        replacement = ", ".join(dict.fromkeys(kept_parts))  # unique, order preserved
        # get character span of the full address fragment
        start_char = doc[start_tok].idx
        end_char = doc[end_tok - 1].idx + len(doc[end_tok - 1])
        original_span = text[start_char:end_char]

        # avoid overlapping replacements by collecting and processing later
        spans_to_replace.append((start_char, end_char, replacement))

    # sort by start position descending to replace safely
    spans_to_replace.sort(key=lambda x: x[0], reverse=True)
    for start_char, end_char, repl in spans_to_replace:
        text = text[:start_char] + repl + text[end_char:]

    return text

# --------------------------------------------------
# Main
# --------------------------------------------------

def anonymize_transcript(transcript_json):
    private_json = []

    for segment in transcript_json:
        seg = segment.copy()
        text = seg.get("text", "")

        # 1. hide ID card, passport, phone numbers
        text = anonymize_regex(text)

        # 2. hide names only
        text = anonymize_entities(text)

        # 3. redact addresses, keeping city and country
        text = redact_addresses(text)

        seg["text"] = text
        private_json.append(seg)

    return private_json

# --------------------------------------------------
# Example usage (unchanged)
# --------------------------------------------------

with open("/content/transcript_dia03sce1SA.json", "r", encoding="utf8") as f:
    transcript = json.load(f)

private_transcript = anonymize_transcript(transcript)

with open("private_transcript.json", "w", encoding="utf8") as f:
    json.dump(private_transcript, f, indent=2, ensure_ascii=False)

with open("mapping.json", "w", encoding="utf8") as f:
    json.dump(reverse_mapping, f, indent=2, ensure_ascii=False)

print("Done.")
print("Private transcript -> private_transcript.json")
print("Mapping -> mapping.json")









