# -*- coding: utf-8 -*-
"""RAG_Qdrant_Summary_with_final_JSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQTyh4W1RP2yxrA88pmGBTeIo-uhlmMZ
"""

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import os
os.environ["HF_TOKEN"] = "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"

os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"

!pip install -q qdrant-client sentence-transformers

!pip install -U bitsandbytes>=0.46.1

HF_TOKEN = "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"

# ==============================
# 1. Imports
# ==============================
import json
import re
import torch
import gc
import numpy as np
from transformers import AutoTokenizer, AutoModel, AutoModelForCausalLM, BitsAndBytesConfig
from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct, VectorParams, Distance

with open("/content/transcript_dia03sce1SA.json", "r") as f:
    segments = json.load(f)

full_text = ""
for seg in segments:
    speaker = seg.get("speaker", "UNKNOWN")
    text = seg.get("text", "").strip()
    if text:
        full_text += f"{speaker}: {text}\n"

CHUNK_SIZE = 500
OVERLAP = 50

def chunk_text(text, chunk_size=CHUNK_SIZE, overlap=OVERLAP):
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start = end - overlap
        if start >= len(text):
            break
    return chunks

chunks = chunk_text(full_text)
print(f"Created {len(chunks)} chunks.")



import torch
import gc
from transformers import AutoTokenizer, AutoModel
from qdrant_client import QdrantClient
from qdrant_client.http.models import VectorParams, Distance, PointStruct

EMBED_MODEL_NAME = "Qwen/Qwen3-Embedding-4B"
embed_model = None
tokenizer_emb = None

def load_embedder():
    global embed_model, tokenizer_emb
    if embed_model is None:
        tokenizer_emb = AutoTokenizer.from_pretrained(EMBED_MODEL_NAME)
        if tokenizer_emb.pad_token is None:
            tokenizer_emb.pad_token = tokenizer_emb.eos_token

        device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Loading embedder on {device.upper()}...")
        embed_model = AutoModel.from_pretrained(EMBED_MODEL_NAME).to(device)
        embed_model.eval()
    return tokenizer_emb, embed_model

def unload_embedder():
    global embed_model, tokenizer_emb
    if embed_model is not None:
        if torch.cuda.is_available():
            embed_model.to("cpu")
            torch.cuda.empty_cache()
        del embed_model
        del tokenizer_emb
        embed_model = None
        tokenizer_emb = None
        gc.collect()
        print("Embedder unloaded and GPU memory freed")

def get_embedding(text):
    inputs = tokenizer_emb(text, return_tensors="pt", truncation=True, max_length=512, padding=True)
    inputs = {k: v.to(embed_model.device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = embed_model(**inputs)
    # Mean pooling over sequence length -> shape (batch, hidden_size)
    return outputs.last_hidden_state.mean(dim=1).cpu().float().numpy()[0].tolist()

# ----------------------------------------------------------------------
# 1. Load the embedder first to know the correct vector size
# ----------------------------------------------------------------------
print("Loading embedder to determine vector size...")
load_embedder()
vector_size = embed_model.config.hidden_size  # This will be 2560 for this model
print(f"Detected embedding dimension: {vector_size}")

# ----------------------------------------------------------------------
# 2. Create the Qdrant collection with the correct size
# ----------------------------------------------------------------------
client = QdrantClient(":memory:")
collection_name = "transcript_chunks"

# If the collection already exists (in persistent storage), drop it first.
# For in-memory, it's fresh, so no need, but if reusing, use:
# client.delete_collection(collection_name)

client.create_collection(
    collection_name=collection_name,
    vectors_config=VectorParams(size=vector_size, distance=Distance.COSINE),
)

# ----------------------------------------------------------------------
# 3. Generate embeddings and upload
# ----------------------------------------------------------------------
points = []
for idx, chunk in enumerate(chunks):
    emb = get_embedding(chunk)
    points.append(PointStruct(id=idx, vector=emb, payload={"text": chunk}))
client.upsert(collection_name=collection_name, points=points)
print(f"Uploaded {len(points)} chunks.")

# ----------------------------------------------------------------------
# 4. Free GPU memory for your LLM later
# ----------------------------------------------------------------------
unload_embedder()

def retrieve(query, top_k=5):
    # Load just for the query embedding
    load_embedder()
    query_emb = get_embedding(query)
    unload_embedder()  # free immediately

    results = client.query_points(
        collection_name=collection_name,
        query=query_emb,
        limit=top_k,
    )
    return [hit.payload["text"] for hit in results.points]

MODEL_NAME = "Qwen/Qwen3-8B"
tokenizer_llm = AutoTokenizer.from_pretrained(MODEL_NAME, token=HF_TOKEN)
if tokenizer_llm.pad_token is None:
    tokenizer_llm.pad_token = tokenizer_llm.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
)
model_llm = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    token=HF_TOKEN,
)

def ask_question(question, conversation_history=None, max_new_tokens=2048):
    if conversation_history is None:
        messages = [{"role": "user", "content": question}]
    else:
        messages = conversation_history + [{"role": "user", "content": question}]

    inputs = tokenizer_llm.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    )
    inputs = {k: v.to(model_llm.device) for k, v in inputs.items()}

    with torch.no_grad():
        # outputs = model_llm.generate(
        #     **inputs,
        #     max_new_tokens=max_new_tokens,
        #     temperature=0.7,
        #     top_p=0.9,
        #     do_sample=True,
        #     repetition_penalty=1.05,
        # )


        outputs = model_llm.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            temperature=None,
            top_p=None,
            repetition_penalty=1.0,
            )
    generated_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    return tokenizer_llm.decode(generated_tokens, skip_special_tokens=True)

def generate_summary(transcript: str) -> str:
    truncated = transcript[:4000]
    prompt = f"""
    You are an expert conversation summarizer.

    The transcript below has been PRIVACY-PRESERVED.

    Personal information has been intentionally replaced with placeholders such as:

    <PERSON_1>
    <CUSTOMER>
    <CHILD_1>
    <CITY_1>
    <COUNTRY_1>
    <LANGUAGE_1>
    <EMPLOYER_1>
    <SCHOOL_1>
    <EMAIL_1>
    <PHONE_1>

    IMPORTANT RULES:

    1. Treat every placeholder as the ORIGINAL value.
      For example:
      - "<COUNTRY_1>" is the customer's actual birth country.
      - "<CITY_1>" is the customer's actual city.
      - "<EMPLOYER_1>" is the customer's actual employer.

    2. NEVER replace placeholders with words such as:
      - anonymous
      - unknown
      - redacted
      - hidden

    3. NEVER invent or guess the original values.

    4. Preserve placeholders exactly as they appear.

    5. Summarize ONLY information explicitly present in the transcript.

    6. Do NOT infer facts that are not stated.

    7. Do NOT include reasoning.

    8. Do NOT output <think> tags.

    9. Return ONLY the summary text.

    Write a concise factual summary (maximum 150 words) covering:

    • Main topics discussed
    • Important customer circumstances
    • Decisions made
    • Advice provided by the advisor
    • Action items or next steps

    Transcript
    -------------------------
    {truncated}
    -------------------------

    Summary:
    """
    return ask_question(prompt, max_new_tokens=256).strip()

print("Generating conversation summary...")
summary = generate_summary(full_text)
print(f"Summary generated ({summary} ).")

import re

def clean_answer(text: str) -> str:
    """
    Remove all think tags and markdown fences, then return the cleaned answer.
    If nothing remains, return the default.
    """
    # Remove content between <think> and </think> (including both tags)
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
    # Remove any leftover <think> that has no closing tag (from tag to end)
    text = re.sub(r'<think>.*', '', text, flags=re.DOTALL)
    # Remove markdown code fences
    text = text.replace("```json", "").replace("```", "").strip()
    # If nothing is left, use the default
    if not text:
        text = "Not mentioned in transcript."
    return text


def generate_additional_information(
    transcript: str,
    previous_answers: dict,
    max_new_tokens: int = 256,
) -> str:
    """
    Generate ONLY additional information that has NOT already been captured
    by the structured questionnaire.
    """

    previous = json.dumps(previous_answers, indent=2, ensure_ascii=False)

    prompt = f"""
    You are an expert analyst extracting metadata from a PRIVACY-PRESERVING (ANONYMIZED) customer-advisor conversation.

    Your task is to produce ONLY the value for:

    "Any Additional Information"

    ====================================================
    IMPORTANT
    ====================================================

    The transcript has been intentionally anonymized.

    Personal information has been replaced with placeholders such as:

    <PERSON_1>
    <CUSTOMER>
    <CHILD_1>
    <CITY_1>
    <COUNTRY_1>
    <LANGUAGE_1>
    <EMPLOYER_1>
    <SCHOOL_1>
    <EMAIL_1>
    <PHONE_1>

    Treat these placeholders exactly as the original values.

    Never replace placeholders.
    Never infer the original values.
    Never ignore placeholders.

    ====================================================
    QUESTIONNAIRE ANSWERS
    ====================================================

    {previous}

    ====================================================
    TRANSCRIPT
    ====================================================

    {transcript}

    ====================================================
    TASK
    ====================================================

    The questionnaire already captures structured information such as:

    - Contact method
    - Immigration reason
    - Customer background
    - Education
    - Birth country
    - Language
    - Domicile
    - Employment status
    - Duration in Finland
    - Visit contents
    - Purpose of visit
    - Referral destination

    DO NOT repeat or paraphrase information already represented by these fields.

    Return ONLY genuinely NEW information that is useful but does not naturally belong to any questionnaire field.

    Examples of valid additional information:

    • Special customer circumstances
    • Exceptional constraints
    • Important follow-up plans
    • Important contextual observations
    • Decisions that do not fit existing questionnaire fields
    • Process-specific details not already captured
    • Relevant information that may help future advisors

    Do NOT include:

    • Reworded questionnaire answers
    • Duplicate information
    • Personal opinions
    • Assumptions
    • Guesses
    • Explanations of placeholders

    If there is no genuinely new information beyond the questionnaire, return EXACTLY:

    Not mentioned in transcript.

    ====================================================
    OUTPUT RULES
    ====================================================

    - Return ONLY the answer.
    - Do NOT return JSON.
    - Do NOT output reasoning.
    - Do NOT output <think>.
    - Do NOT output markdown.
    - Do NOT explain your answer.
    """

    response = ask_question(prompt, max_new_tokens=max_new_tokens).strip()
    return clean_answer(response)


def generate_feedback(
    transcript: str,
    previous_answers: dict,
    max_new_tokens: int = 256,
) -> str:
    """
    Generate ONLY feedback or advisor observations that are not already
    represented in the questionnaire.
    """
    previous = json.dumps(previous_answers, indent=2, ensure_ascii=False)

    prompt = f"""
    You are an expert analyst extracting metadata from a PRIVACY-PRESERVING (ANONYMIZED) customer-advisor conversation.

    Your task is to produce ONLY the value for:

    "Any other Feedback"

    ====================================================
    IMPORTANT
    ====================================================

    The transcript has been intentionally anonymized.

    Personal information has been replaced with placeholders such as:

    <PERSON_1>
    <CUSTOMER>
    <CHILD_1>
    <CITY_1>
    <COUNTRY_1>
    <LANGUAGE_1>
    <EMPLOYER_1>
    <SCHOOL_1>
    <EMAIL_1>
    <PHONE_1>

    Treat these placeholders exactly as the original values.

    Never replace placeholders.
    Never infer the original values.
    Never ignore placeholders.

    ====================================================
    QUESTIONNAIRE ANSWERS
    ====================================================

    {previous}

    ====================================================
    TRANSCRIPT
    ====================================================

    {transcript}

    ====================================================
    TASK
    ====================================================

    The questionnaire already captures structured facts about the conversation.
    DO NOT repeat or paraphrase information already represented by the questionnaire fields.

    Return ONLY genuinely NEW feedback that is useful but does not naturally belong to any questionnaire field.

    Examples of valid feedback:

    • Advisor comments
    • Recommendations
    • Observations
    • Suggestions for improving the service
    • Customer satisfaction comments
    • Communication issues
    • Process improvements
    • Anything that would normally be written as internal feedback

    Do NOT include:

    • Reworded questionnaire answers
    • Duplicate information
    • Conversation summaries
    • Personal opinions
    • Assumptions
    • Guesses
    • Explanations of placeholders

    If there is no genuinely new feedback beyond the questionnaire, return EXACTLY:

    Not mentioned in transcript.

    ====================================================
    OUTPUT RULES
    ====================================================

    - Return ONLY the answer.
    - Do NOT return JSON.
    - Do NOT output reasoning.
    - Do NOT output <think>.
    - Do NOT output markdown.
    - Do NOT explain your answer.
    """

    response = ask_question(prompt, max_new_tokens=max_new_tokens).strip()
    return clean_answer(response)

# def generate_feedback(
#     transcript: str,
#     previous_answers: dict,
#     max_new_tokens: int = 256,
# ) -> str:
#     """
#     Generate ONLY feedback or advisor observations that are not already
#     represented in the questionnaire.
#     """
#     previous = json.dumps(previous_answers, indent=2, ensure_ascii=False)

#     prompt = f"""
# You are extracting metadata from a customer-service conversation.

# Your task is to answer ONLY the field: "Any other Feedback".

# You are given:

# 1. The transcript.
# 2. The questionnaire answers that have already been extracted.

# ========================
# QUESTIONNAIRE ANSWERS
# ========================

# {previous}

# ========================
# TRANSCRIPT
# ========================

# {transcript}

# ========================
# INSTRUCTIONS
# ========================

# The questionnaire already contains the structured facts.

# Do NOT repeat them.

# Only generate feedback if the transcript explicitly contains:
# - advisor comments
# - recommendations
# - observations
# - suggestions for improving the service
# - customer satisfaction comments
# - communication issues
# - process improvements
# - anything that would normally be written as internal feedback.

# Do NOT summarize the conversation.
# Do NOT repeat facts already covered in the questionnaire.

# If there is no explicit feedback beyond what is already captured, respond EXACTLY with:

# Not mentioned in transcript.

# CRITICAL: Do NOT include any reasoning, explanation, additional text, markdown, or tags like <think>. Output ONLY the answer itself.
# """

#     response = ask_question(prompt, max_new_tokens=max_new_tokens).strip()

#     # Remove anything from the first <think> tag onward (robust fallback)
#     if "<think>" in response:
#         response = response.split("<think>", 1)[0].strip()
#         if not response:
#             response = "Not mentioned in transcript."

#     # Remove markdown fences
#     response = response.replace("```json", "").replace("```", "").strip()

#     return response

def extract_json(text):
    match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if match:
        json_str = match.group(1)
    else:
        start = text.find('{')
        end = text.rfind('}')
        if start != -1 and end != -1:
            json_str = text[start:end+1]
        else:
            raise ValueError("No JSON object found")
    return json.loads(json_str)

"""## All questions grouped"""

groups = [
    {
        "id": "GROUP 1",
        "questions": [
            {
                "id": "Ques.5",
                "text": "What is the contact method used by Advisee(s)?",
                "options": [
                    "a) Visit for guidance/advice in-person",
                    "b) Telephone (eg. call, WhatsApp etc)",
                    "c) Written Contact (eg. email, WhatsApp, social media etc)",
                    "d) Remote Connection",
                    "e) Electronic service (eg. forms)",
                    "f) Field Work (if yes then where)"
                ]
            },
            {
                "id": "Ques.6",
                "text": "Heard from the guidance/advice position (if other where?)",
                "options": None
            }
        ]
    },
    {
        "id": "GROUP 2",
        "questions": [
            {
                "id": "Ques.10",
                "text": "Reason for Immigration",
                "options": None
            }
        ]
    },
    {
        "id": "GROUP 3",
        "questions": [
            {
                "id": "Ques.11",
                "text": "Additional Information about the customers",
                "options": [
                    "a) Illiterate",
                    "b) Paperless",
                    "c) Tourist",
                    "d) Ukraine Crisis",
                    "e) If something else type"
                ],
                "allow_other": True   # flag: if none apply, provide custom description
            },
            {
                "id": "Ques.14",
                "text": "Education Level",
                "options": None
            }
        ]
    },
    {
        "id": "GROUP 4",
        "questions": [
            {
                "id": "Ques.12",
                "text": "Customer birth country",
                "options": None
            },
            {
                "id": "Ques.13",
                "text": "Mother Tongue/Language",
                "options": None
            },
            {
                "id": "Ques.16",
                "text": "Customer Domicile",
                "options": None
            }
        ]
    },
    {
        "id": "GROUP 5",
        "questions": [
            {
                "id": "Ques.15",
                "text": "Position in labour market",
                "options": [
                    "a) No Information",
                    "b) Working in the open market",
                    "c) Working outside the open market (eg.: wage subsidy, work trail)",
                    "d) Entrepreneur",
                    "e) Unemployed",
                    "f) In labour policy training (including integration training)",
                    "g) Student",
                    "h) Outside the labour market (eg.: stay-home-parent, retiree)",
                    "i) Planning to move to Finland"
                ]
            }
        ]
    },
    {
        "id": "GROUP 6",
        "questions": [
            {
                "id": "Ques.17",
                "text": "Duration of residence in Finland",
                "options": [
                    "a) No information",
                    "b) Does not live in Finland",
                    "c) Less than 3 years",
                    "d) 3-5 years",
                    "e) More than 5 years"
                ]
            }
        ]
    },
    {
        "id": "GROUP 7",
        "questions": [
            {
                "id": "Ques.18",
                "text": "Contents of the customer visit:",
                "options": [
                    "a) Residence",
                    "b) Benefits (eg.: Kela)",
                    "c) Hobbies & Leisures",
                    "d) Matters related to education",
                    "e) Crisis situations (family crisis, violent situations)",
                    "f) Matters related to immigration process (eg.: residence permit)",
                    "g) Legal Matters",
                    "h) Family life (eg.: children's school, early childhood education, relationships)",
                    "i) Police matters",
                    "j) Social Affairs (eg.: social work, guidance)",
                    "k) Studying Finnish/Swedish",
                    "l) Finance (eg.: taxation, debt, bills, banking, and customer affairs)",
                    "m) Health care",
                    "n) Working conditions (eg.: occupational health safety)",
                    "o) Work (eg.: TE, Job search, etc)",
                    "p) Career Guidance",
                    "q) If other, then type"
                ],
                "allow_other": True
            },
            {
                "id": "Ques.19",
                "text": "Purpose of visit",
                "options": [
                    "a) Initial Interview",
                    "b) Digital Help",
                    "c) Language Support",
                    "d) Filling out the forms",
                    "e) Clarification of decisions and process",
                    "f) Group info",
                    "g) Contacting the authority of another country",
                    "h) Others"
                ],
                "allow_other": True
            }
        ]
    },
    {
        "id": "GROUP 8",
        "questions": [
            {
                "id": "Ques.21",
                "text": "Where the customer is directed",
                "options": [
                    "a) Trade-unions, occupational safety and health",
                    "b) Lawyer and legal aid services",
                    "c) Real estate agency/real estate, housing agency",
                    "d) Digital and Population Information Agency",
                    "e) Victims of human trafficking",
                    "f) help system",
                    "g) Organizations and associations",
                    "h) School activity (basic education)",
                    "i) Crisis services",
                    "j) Municipal immigrant and integration services",
                    "k) Finnish Immigration Service (Migri)",
                    "l) Youth services (e.g., Ohjaamo)",
                    "m) Educational institution (secondary school, higher education or other)",
                    "n) Police",
                    "o) Congregations and other religious communities",
                    "p) Social and family services",
                    "q) Embassy",
                    "r) TE services",
                    "s) Health services",
                    "t) Customs",
                    "u) Early childhood education",
                    "v) Tax office",
                    "w) Shared service point",
                    "x) Support services for entrepreneurs",
                    "y) Companies/employers",
                    "z) Other entities",
                    "aa) Case closed",
                    "ab) Customer service continues/Make a new appointment",
                    "ac) Guidance and counseling service in another location"   # Fixed missing option
                ],
                "allow_other": False  # We have all options; if not found, output "Not mentioned"
            }
        ]
    }

]





# ==============================
# 10. Process each group with full-text answers
# ==============================

all_flat_results = {}

instruction = """
    You are an expert analyst extracting structured data from a PRIVACY-PRESERVING (ANONYMIZED) customer-advisor conversation.

    ====================================================
    IMPORTANT – ANONYMIZED TRANSCRIPT
    ====================================================

    The transcript has been intentionally anonymized.

    Personal information has been replaced with placeholders such as:

    <PERSON_1>
    <CUSTOMER>
    <CHILD_1>
    <CITY_1>
    <COUNTRY_1>
    <LANGUAGE_1>
    <EMPLOYER_1>
    <SCHOOL_1>
    <EMAIL_1>
    <PHONE_1>

    Treat these placeholders exactly as the original values.

    Never replace placeholders.
    Never infer the original values.
    Never ignore placeholders.
    Always output them exactly as they appear in the transcript.

    ====================================================
    EXTRACTION RULES
    ====================================================

    1. Questions with listed options
    - Return the COMPLETE option text exactly as written in the options list.
    - Include both the option letter and its description.
    - Example:
        Correct: "u) Early childhood education"
        Wrong: "u"

    2. Questions containing an "If something else type" or "If other, then type" option
    - If one of the listed options clearly matches the transcript, return the full option text.
    - If NONE of the listed options apply, DO NOT return:
          "e) If something else type"
      or
          "q) If other, then type".
    - Instead, extract and return a short custom description from the transcript.
    - If there is no relevant information in the transcript, return:
          "Not mentioned in transcript."

    Example:
    Transcript:
    "The customer is an asylum seeker."

    Correct:
    "Asylum seeker"

    Wrong:
    "e) If something else type"

    3. Question-specific rule for Ques.21) Where the customer is directed
    - The answer MUST be exactly one of the provided options.
    - Return the FULL option text.
    - Never invent a destination.
    - If no destination is explicitly mentioned, return:
          "Not mentioned in transcript."

    4. Questions without options
    - Provide a concise factual answer using only the transcript.
    - Do NOT infer or guess.
    - If the answer contains a placeholder (e.g., <CITY_1>), keep it exactly as is.

    5. Missing information
    - If the transcript does not contain enough evidence, return:
          "Not mentioned in transcript."

    6. General rules
    - Use ONLY the supplied summary and retrieved transcript.
    - Do NOT hallucinate.
    - Return ONLY a valid JSON object.
    - Use the EXACT question text as the JSON key.
    - Never alter, remove, or replace placeholders in the returned values.
"""
for group in groups:

    group_id = group["id"]
    print(f"\n--- Processing {group_id} ---")

    # -------------------------------------------------------
    # Build retrieval query
    # -------------------------------------------------------
    query_text = ""

    for q in group["questions"]:
        query_text += q["text"] + "\n"

        if q.get("options"):
            query_text += "Options: " + ", ".join(q["options"]) + "\n"

        query_text += "\n"

    # -------------------------------------------------------
    # Retrieve relevant transcript chunks
    # -------------------------------------------------------
    retrieved_chunks = retrieve(query_text, top_k=5)
    context = "\n\n".join(retrieved_chunks)

    # -------------------------------------------------------
    # Build question block
    # -------------------------------------------------------
    questions_with_ids = ""

    for q in group["questions"]:

        questions_with_ids += f"{q['id']}) {q['text']}\n"

        if q.get("options"):

            questions_with_ids += "Options:\n"

            for opt in q["options"]:
                questions_with_ids += f"  {opt}\n"

            if q.get("allow_other", False):

                questions_with_ids += """
NOTE:
- If none of the listed options apply, DO NOT choose
  "If something else type" or "If other, then type".
- Instead, extract a short custom answer from the transcript.
"""

            else:

                questions_with_ids += """
NOTE:
- The answer MUST be one of the listed options.
- Otherwise return:
  "Not mentioned in transcript."
"""

        questions_with_ids += "\n"

    # -------------------------------------------------------
    # Context
    # -------------------------------------------------------
    combined_context = f"""
Summary of the conversation:
{summary}

Relevant transcript excerpts:
{context}
"""

    # -------------------------------------------------------
    # Prompt
    # -------------------------------------------------------
    prompt = f"""
      You are an expert conversation analyst extracting structured information from a PRIVACY-PRESERVING (ANONYMIZED) customer-advisor conversation.

      IMPORTANT:
      - The conversation has been intentionally anonymized before being provided to you.
      - Personal information has been replaced with placeholders enclosed in angle brackets.
      - These placeholders represent the ORIGINAL values and MUST be treated as factual information.

      Examples of placeholders include (but are not limited to):

      <PERSON_1>
      <CUSTOMER>
      <CHILD_1>
      <SPOUSE_1>
      <PARENT_1>

      <CITY_1>
      <COUNTRY_1>
      <ADDRESS_1>

      <LANGUAGE_1>

      <EMPLOYER_1>
      <ORG_1>
      <SCHOOL_1>
      <UNIVERSITY_1>
      <HOSPITAL_1>

      <PHONE_1>
      <EMAIL_1>
      <PASSPORT_1>
      <CUSTOMER_ID_1>

      Rules:

      1. Treat placeholders exactly as if they were the original values.

      2. NEVER replace placeholders with:
        - "Unknown"
        - "Anonymous"
        - "Redacted"
        - "Not mentioned"
        - Any invented value

      3. If a placeholder answers the question, return the placeholder exactly as it appears.

      Example:

      Transcript:
      "I was born in <COUNTRY_1>."

      Correct:
      "Customer birth country": "<COUNTRY_1>"

      NOT

      "Customer birth country": "Not mentioned"

      Another example:

      Transcript:
      "I currently live in <CITY_2>, Finland."

      Correct:
      "Customer Domicile": "<CITY_2>, Finland"

      4. Use ONLY the information provided in the conversation.
      Do not infer, guess, or invent missing information.

      5. If the transcript truly does not contain enough information to answer a question, return exactly the value specified by the instructions (for example, "Not mentioned in transcript." or "Not determined").

      6. Do NOT output reasoning.

      7. Do NOT output <think> tags.

      8. Return ONLY the final JSON.

      --------------------------------------------------------
      Conversation Context
      --------------------------------------------------------

      {combined_context}

      --------------------------------------------------------
      Questions
      --------------------------------------------------------

      {questions_with_ids}

      --------------------------------------------------------
      Instructions
      --------------------------------------------------------

      {instruction}

      Return ONLY a valid JSON object.

      The JSON keys MUST exactly match the question texts.

      Do not include markdown.

      Do not include explanations.

      Do not include any additional text.
      """

    # -------------------------------------------------------
    # Ask LLM
    # -------------------------------------------------------
    answer = ask_question(prompt, max_new_tokens=2048)

    # -------------------------------------------------------
    # Parse JSON
    # -------------------------------------------------------
    # try:
    #     result = extract_json(answer)


    try:
        result = extract_json(answer)

        cleaned_result = {}

        for key, value in result.items():

            # Remove "Ques.15) "
            clean_key = re.sub(r"^Ques\.\d+\)\s*", "", key).strip()

            # Remove option labels like "a) ", "b) ", ..., "aa) "
            if isinstance(value, str):
                clean_value = re.sub(
                    r"^[a-z]{1,2}\)\s*",
                    "",
                    value.strip(),
                    flags=re.IGNORECASE,
                )
            else:
                clean_value = value

            cleaned_result[clean_key] = clean_value

        result = cleaned_result

    except Exception as e:

        print(f"Failed to parse JSON for {group_id}")
        print(e)
        print("\nRaw model output:\n")
        print(answer)

        result = {
            q["text"]: "Not determined"
            for q in group["questions"]
        }

    # -------------------------------------------------------
    # Save group result
    # -------------------------------------------------------
    with open(f"output_{group_id.replace(' ', '_')}.json", "w") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    # -------------------------------------------------------
    # Merge into final result
    # -------------------------------------------------------
    for key, value in result.items():

        if key in all_flat_results:
            print(f"WARNING: Duplicate key detected: {key}")

        all_flat_results[key] = value

    print(f"Finished {group_id}")





  # ==========================================================
# Generate Additional Information
# ==========================================================

print("\nGenerating additional information...")

additional_context = "\n\n".join(
    retrieve(
        "additional information feedback follow up advisor recommendation",
        top_k=5,
    )
)

all_flat_results["Any Additional Information"] = (
    generate_additional_information(
        transcript=additional_context,
        previous_answers=all_flat_results,
    )
)

# ==========================================================
# Generate Feedback
# ==========================================================

print("Generating feedback...")

feedback_context = "\n\n".join(
    retrieve(
        "feedback advisor recommendation improvement follow up comments",
        top_k=5,
    )
)

# If you have a separate feedback function
all_flat_results["Any other Feedback"] = (
    generate_feedback(
        transcript=feedback_context,
        previous_answers=all_flat_results,
    )
)

# ----------------------------------------------------------
# If you DO NOT have generate_feedback(), use this instead:
#
# all_flat_results["Any other Feedback"] = (
#     generate_additional_information(
#         transcript=feedback_context,
#         previous_answers=all_flat_results,
#     )
# )
# ----------------------------------------------------------

# ==========================================================
# Save final JSON
# ==========================================================

with open("all_results.json", "w", encoding="utf-8") as f:
    json.dump(all_flat_results, f, indent=2, ensure_ascii=False)

print("\nAll groups processed.")
print("Flat JSON saved as 'all_results.json'.")

print("\nGenerating additional information...")

additional_context = "\n\n".join(
    retrieve(
        "additional information feedback follow up advisor recommendation",
        top_k=5,
    )
)

all_flat_results["Any Additional Information"] = (
    generate_additional_information(
        transcript=additional_context,
        previous_answers=all_flat_results,
    )
)

print("Generating feedback...")

feedback_context = "\n\n".join(
    retrieve(
        "feedback advisor recommendation improvement follow up comments",
        top_k=5,
    )
)

all_flat_results["Any other Feedback"] = (
    generate_feedback(
        transcript=feedback_context,
        previous_answers=all_flat_results,
    )
)

# Save updated JSON
with open("all_results.json", "w", encoding="utf-8") as f:
    json.dump(all_flat_results, f, indent=2, ensure_ascii=False)

print("Updated successfully!")















